
[[constraint]]
  branch = "master"
  name = "github.com/shibukawa/configdir"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/lann/mpris2-go"

[[constraint]]
  branch = "master"
  name = "github.com/silvercory/discordrpc-go"